import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import './globals.css';
import Link from 'next/link';
import { Navbar, Container, Button } from 'react-bootstrap';
import { signOut, auth } from '@/auth';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sesion = await auth();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar bg="dark" variant="dark" expand="lg" sticky="top">
          <Container>
            <div>
              <Link href="/" passHref>
                <h1>Dashboard-task4</h1>
              </Link>
            </div>

            {sesion ? (
              <form
                action={async () => {
                  'use server';
                  await signOut({ redirectTo: '/' });
                }}
              >
                <span style={{ color: 'gray', marginRight: '10px' }}>
                  {sesion.user?.email}
                </span>
                <Button type="submit" variant="primary">
                  Sign Out
                </Button>
              </form>
            ) : (
              <div>
                <Link href="/login">
                  <Button variant="primary">Log in</Button>
                </Link>
                <Link href="/signup">
                  <Button variant="primary">Sign up</Button>
                </Link>
              </div>
            )}
          </Container>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
